{{- range .Values.images }}
apiVersion: apps/v1
kind: Deployment
metadata:
 name: {{ .name }}
spec:
 replicas: 1
 selector:
  matchLabels:
   app: {{ .name }}
 template:
  metadata:
   labels:
    app: {{ .name }}
  spec:
   containers:
     - name: {{ .name }}
       image: {{ .image }}
       {{- if .env }}
          env:
            {{- range .env }}
            - name: {{ .name }}
              value: {{ .value | quote }}
            {{- end }}
          {{- end }}
          ports:
            - containerPort: {{ .port }}
---
{{- end }}
