{{- range .Values.images }}
apiVersion: apps/v1
kind: Deployment
metadata:
 name: {{ .name }}
spec:
 replicas: 1
 selector:
  matchLabels:
   app: {{ .name }}
 template:
  metadata:
   labels:
    app: {{ .name }}
  spec:
   containers:
    - name: {{ .name }}
      image: {{ .image }}
      ports:
       - containerPort: {{ .port }}
      {{- range .Values.images.env }}
      env:
        - name: {{ .name }}
          value: {{ .value }}
        - name: {{ .name }}
          value: {{ .value }}
        - name: {{ .name }}
          value: {{ .value }}
      ---
     {{- end }}
---
{{- end }}
