apiVersion: v1
kind: Service
metadata:
  name: postgres-db
  namespace: rental-svc
  labels:
    app: postgres-db
spec:
  type: ClusterIP
  selector:
    app: postgres-db
  ports:
    - port: 5432
      protocol: TCP
      targetPort: 5432

