apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: postgres-db
  name: postgres-db
  namespace: rental-svc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-db
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: postgres-db
    spec:
      containers:
      - image: postgres:15
        name: postgres-db
        resources: {}
        ports:
           - containerPort: 5432
        env:
         - name: POSTGRES_USER
           value: root
         - name: POSTGRES_PASSWORD
           value: rootpassword
         - name: POSTGRES_DB
           value: postgress

status: {}
