images:
 - name: api-gateway
   image: prashanth7993/api-gateway:latest
   namespace: rental-svc
   port: 9000
   database: apigateway_db
   env:
     - name: SPRING_DATASOURCE_URL
       value: jdbc:postgresql://postgres-db:5432/apigateway_db
     - name: SPRING_DATASOURCE_USERNAME
       value: root
     - name: SPRING_DATASOURCE_PASSWORD
       value: rootpassword

 - name: authentication-service
   image: prashanth7993/authentication-service:latest
   port: 9099
   namespace: rental-svc
   database: authentication-service
   env:
     - name: SPRING_DATASOURCE_URL
       value: jdbc:postgresql://postgres-db:5432/authentication-service
     - name: SPRING_DATASOURCE_USERNAME
       value: root
     - name: SPRING_DATASOURCE_PASSWORD
       value: rootpassword
 - name: bookings-service
   image: prashanth7993/bookings-service:latest
   port: 9595
   namespace: rental-svc
   database: bookings-service
   env:
     - name: SPRING_DATASOURCE_URL
       value: jdbc:postgresql://postgres-db:5432/bookings-service
     - name: SPRING_DATASOURCE_USERNAME
       value: root
     - name: SPRING_DATASOURCE_PASSWORD
       value: rootpassword
 - name: config-server
   image: prashanth7993/config-server:latest
   port: 8088
   namespace: rental-svc
   database: configservice_db
   env:
     - name: SPRING_DATASOURCE_URL
       value: jdbc:postgresql://postgres-db:5432/configservice_db
     - name: SPRING_DATASOURCE_USERNAME
       value: root
     - name: SPRING_DATASOURCE_PASSWORD
       value: rootpassword
 - name: coupon-service
   image: prashanth7993/coupon-service:latest
   port: 9097
   namespace: rental-svc
   database: coupon-service
   env:
     - name: SPRING_DATASOURCE_URL
       value: jdbc:postgresql://postgres-db:5432/coupon-service
     - name: SPRING_DATASOURCE_USERNAME
       value: root
     - name: SPRING_DATASOURCE_PASSWORD
       value: rootpassword
 - name: customer-support
   image: prashanth7993/customer-support:latest
   port: 8090
   namespace: rental-svc
   database: customer-support
   env:
     - name: SPRING_DATASOURCE_URL
       value: jdbc:postgresql://postgres-db:5432/customer-support
     - name: SPRING_DATASOURCE_USERNAME
       value: root
     - name: SPRING_DATASOURCE_PASSWORD
       value: rootpassword
 - name: mail-service
   image: prashanth7993/mail-service:latest
   port: 9098
   namespace: rental-svc
   database: mailsvc_db
   env:
     - name: SPRING_DATASOURCE_URL
       value: jdbc:postgresql://postgres-db:5432/mailsvc_db
     - name: SPRING_DATASOURCE_USERNAME
       value: root
     - name: SPRING_DATASOURCE_PASSWORD
       value: rootpassword
 - name: payment-service
   image: prashanth7993/payment-service:latest
   port: 9696
   namespace: rental-svc
   database: payment-service
   env:
     - name: SPRING_DATASOURCE_URL
       value: jdbc:postgresql://postgres-db:5432/payment-service
     - name: SPRING_DATASOURCE_USERNAME
       value: root
     - name: SPRING_DATASOURCE_PASSWORD
       value: rootpassword
 - name: review-service
   image: prashanth7993/review-service:latest
   port: 9096
   namespace: rental-svc
   database: review-service
   env:
     - name: SPRING_DATASOURCE_URL
       value: jdbc:postgresql://postgres-db:5432/review-service
     - name: SPRING_DATASOURCE_USERNAME
       value: root
     - name: SPRING_DATASOURCE_PASSWORD
       value: rootpassword
 - name: service-registry
   image: prashanth7993/service-registry:latest
   port: 8761
   namespace: rental-svc
   database: registrysvc_db
   env:
     - name: SPRING_DATASOURCE_URL
       value: jdbc:postgresql://postgres-db:5432/registrysvc_db
     - name: SPRING_DATASOURCE_USERNAME
       value: root
     - name: SPRING_DATASOURCE_PASSWORD
       value: rootpassword
 - name: user-service
   image: prashanth7993/user-service:latest
   port: 9848
   namespace: rental-svc
   database: user-service
   env:
     - name: SPRING_DATASOURCE_URL
       value: jdbc:postgresql://postgres-db:5432/user-service
     - name: SPRING_DATASOURCE_USERNAME
       value: root
     - name: SPRING_DATASOURCE_PASSWORD
       value: rootpassword
 - name: vehicles-service
   image: prashanth7993/vehicles-service:latest
   port: 8092
   namespace: rental-svc
   database: vehicles-service
   env:
     - name: SPRING_DATASOURCE_URL
       value: jdbc:postgresql://postgres-db:5432/vehicles-service
     - name: SPRING_DATASOURCE_USERNAME
       value: root
     - name: SPRING_DATASOURCE_PASSWORD
       value: rootpassword
 - name: vendor-service
   image: prashanth7993/vendor-service:latest
   port: 8091
   namespace: rental-svc
   database: vendor-service
   env:
     - name: SPRING_DATASOURCE_URL
       value: jdbc:postgresql://postgres-db:5432/vendor-service
     - name: SPRING_DATASOURCE_USERNAME
       value: root
     - name: SPRING_DATASOURCE_PASSWORD
       value: rootpassword

serviceType: NodePort
