images:
 - name: api-gateway
   image: prashanth7993/api-gateway:latest
   port: 8080
 - name: authentication-service
   image: prashanth7993/authentication-service:latest
   port: 8080
 - name: bookings-service
   image: prashanth7993/bookings-service:latest
   port: 8080
 - name: config-server
   image: prashanth7993/config-server:latest
   port: 8080
 - name: coupon-service
   image: prashanth7993/coupon-service:latest
   port: 8080
 - name: customer-support
   image: prashanth7993/customer-support:latest
   port: 8080
 - name: mail-service
   image: prashanth7993/mail-service:latest
   port: 8080
 - name: payment-service
   image: prashanth7993/payment-service:latest
   port: 8080
 - name: review-service
   image: prashanth7993/review-service:latest
   port: 8080
 - name: service-registry
   image: prashanth7993/service-registry:latest
   port: 8080
 - name: user-service
   image: prashanth7993/user-service:latest
   port: 8080
 - name: vehicles-service
   image: prashanth7993/vehicles-service:latest
   port: 8080
 - name: vendor-service
   image: prashanth7993/vendor-service:latest
   port: 8080

serviceType: NodePort
