{{- range .Values.microservices }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "my-java.fullname" . }}
  labels:
    {{- include "my-java.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "my-java.selectorLabels" . | nindent 4 }}
{{- end }}
